name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - master
      - ab-test/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
#      - uses: actions/cache@v1
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
      - name: build master branch
        run: |
          npm install
          npm run build-branch
      - name: build ab-test branches
        run: |
          git branch -r |
          grep --line-buffered ab-test |
          awk '{split($0,a,"/"); print a[2]"/"a[3]}' |
          xargs -L1 >> ab-test-branches.txt
          while read l; do git checkout "$l"; npm install && npm run build-branch; done < ab-test-branches.txt
      - name: pre-deploy
        uses: navikt/pam-deploy/actions/pre-deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          docker build . --pull -t $IMAGE
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin docker.pkg.github.com
          docker push $IMAGE
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: naiserator.yml
          VARS: naiserator-dev.json
